#!/usr/bin/env python3
"""
Patch ratings in src/data/pokalPlayers.js using scraped data.

  • Clubs scraped from fifaindex  → real player OVR ratings (name-matched)
  • Unscraped 3. Liga clubs       → flat rating 60
  • Regionalliga / amateur clubs  → flat rating 50
  • Removes duplicates from pokalPlayers.js

Usage:
    python scripts/export_pokal_lower_js.py
"""

import sqlite3
import re
import unicodedata
from pathlib import Path

ROOT       = Path(__file__).parent.parent
DB_PATH    = ROOT / "pokal_lower_draft.db"
CLUBS_FILE = ROOT / "data" / "fifaindex_pokal_lower_clubs.txt"
POKAL_JS   = ROOT / "src" / "data" / "pokalPlayers.js"

# fi_club_id → canonical name as it appears in pokalPlayers.js
CLUB_NAME_MAP = {
    110482: "Hallescher FC",
    110501: "SC Verl",
    110532: "SV Waldhof Mannheim",
    526:    "Rot-Weiss Essen",
    110645: "FC Viktoria Köln",
    110194: "SpVgg Bayreuth",
    172:    "SpVgg Unterhaching",
    110592: "FSV Zwickau",
    507:    "Chemnitzer FC",
    110597: "SV Meppen",
    110591: "FC Carl Zeiss Jena",
    167:    "KFC Uerdingen 05",
    100424: "Rot-Weiß Erfurt",
    1829:   "VfB Lübeck",
    110700: "Sportfreunde Lotte",
    1827:   "SV Eintracht Trier 05",
    110526: "TuS Koblenz",
    523:    "1. FC Saarbrücken",
    1950:   "Kickers Offenbach",
    1828:   "Rot-Weiß Oberhausen",
    110500: "Eintracht Braunschweig",
    110169: "SC Fortuna Köln",
}

# Canonical names for unscraped 3. Liga / DFL clubs (??? in the top section)
DRITTE_LIGA_UNSCRAPED = {
    "1. FC Lokomotive Leipzig",
    "TSV Steinbach Haiger",
    "Stuttgarter Kickers",
    "Wuppertaler SV",
    "BFC Dynamo",
    "Türkgücü München",
    "SV Babelsberg 03",
    "SV Rödinghausen",
    "Greifswalder FC",
    "SV Straelen",
    "SV Wacker Burghausen",
}


def normalize(name: str) -> str:
    name = name.replace("ß", "ss").replace("ẞ", "ss")
    nfd = unicodedata.normalize("NFD", name)
    ascii_only = "".join(c for c in nfd if unicodedata.category(c) != "Mn")
    spaced = ascii_only.replace("-", " ").replace(".", " ")
    return re.sub(r" +", " ", re.sub(r"[^a-z ]", "", spaced.lower())).strip()


def build_rating_lookup(con) -> dict:
    """Build {(normalized_name, canonical_club, season_key): best_rating}."""
    lookup: dict = {}
    for fi_club_id, club_name in CLUB_NAME_MAP.items():
        rows = con.execute(
            "SELECT name, season_year, rating FROM scraped_players WHERE fi_club_id=?",
            (fi_club_id,)
        ).fetchall()
        for name, season_year, rating in rows:
            season_key = f"{season_year}-{str(season_year + 1)[2:]}"
            key = (normalize(name), club_name, season_key)
            if key not in lookup or rating > lookup[key]:
                lookup[key] = rating
    return lookup


ENTRY_RE = re.compile(
    r"\{ name: '([^']+)', positions: \[([^\]]+)\], "
    r"seasons: \[\{ club: '([^']+)', season: '([^']+)', rating: \d+ \}\] \}"
)


def main():
    if DB_PATH.exists():
        con = sqlite3.connect(DB_PATH)
        rating_lookup = build_rating_lookup(con)
        con.close()
        print(f"Loaded {len(rating_lookup)} scraped player-season ratings from DB.")
    else:
        rating_lookup = {}
        print("No DB found — using fallback ratings only (60 / 50).")

    src = POKAL_JS.read_text(encoding="utf-8")

    seen: set = set()
    entries_out: list[str] = []
    stats = {"scraped": 0, "dritte": 0, "amateur": 0, "dupes": 0}

    for m in ENTRY_RE.finditer(src):
        name, positions_raw, club, season = m.groups()
        dedup_key = (name, club, season)
        if dedup_key in seen:
            stats["dupes"] += 1
            continue
        seen.add(dedup_key)

        lookup_key = (normalize(name), club, season)
        if lookup_key in rating_lookup:
            rating = rating_lookup[lookup_key]
            stats["scraped"] += 1
        elif club in DRITTE_LIGA_UNSCRAPED:
            rating = 60
            stats["dritte"] += 1
        else:
            rating = 50
            stats["amateur"] += 1

        entries_out.append(
            f"  {{ name: '{name}', positions: [{positions_raw}], "
            f"seasons: [{{ club: '{club}', season: '{season}', rating: {rating} }}] }},"
        )

    output = (
        "// Auto-generated by scripts/export_pokal_lower_js.py — do not edit by hand.\n"
        "// Pokal-only squad data (lower-tier teams) — name + position + rating.\n"
        "// Used for opponent scorer display; not draftable.\n\n"
        "export const POKAL_PLAYERS = [\n"
        + "\n".join(entries_out) + "\n"
        "];\n"
    )

    POKAL_JS.write_text(output, encoding="utf-8")

    total = stats["scraped"] + stats["dritte"] + stats["amateur"]
    print(f"✓ Wrote {total} unique entries to pokalPlayers.js")
    print(f"  {stats['scraped']:4d}  with scraped ratings")
    print(f"  {stats['dritte']:4d}  with 3. Liga fallback (60)")
    print(f"  {stats['amateur']:4d}  with amateur fallback (50)")
    print(f"  {stats['dupes']:4d}  duplicates removed")


if __name__ == "__main__":
    main()
