#!/usr/bin/env python3
"""
Export European player data from european_cups.db to:
  src/data/playersEuropean.js   — same schema as players.js
  src/data/uclParticipants.js   — { club, season, result }
  src/data/uelParticipants.js   — { club, season, result }

Ratings are 0 until filled by a future scrape_fifaindex step.

Usage:
    python scripts/export_european_players_js.py
"""

import sqlite3, re
from pathlib import Path

ROOT    = Path(__file__).parent.parent
DB_PATH = ROOT / "european_cups.db"

def js_str(s) -> str:
    return "'" + str(s or "").replace("\\", "\\\\").replace("'", "\\'") + "'"

def make_id(name: str, tm_id: int) -> str:
    slug = re.sub(r"[^\w\s-]", "", name.lower())
    slug = re.sub(r"[\s_]+", "-", slug).strip("-")
    return f"{slug}-{tm_id}"


def export_participants(con: sqlite3.Connection):
    for comp, var, fname in [
        ("ucl", "UCL_PARTICIPANTS", "uclParticipants.js"),
        ("uel", "UEL_PARTICIPANTS", "uelParticipants.js"),
    ]:
        rows = con.execute(
            "SELECT sc.club_name, s.label, sc.result "
            "FROM season_clubs sc "
            "JOIN seasons s ON s.year = sc.season_year AND s.comp_id = sc.comp_id "
            "WHERE sc.comp_id = ? "
            "ORDER BY sc.season_year, sc.club_name",
            (comp,)
        ).fetchall()

        if not rows:
            print(f"  No data for {comp}, skipping")
            continue

        lines = [
            "// Auto-generated by scripts/export_european_players_js.py",
            "// result: 'winner'|'final'|'sf'|'qf'|'r16'|'r32'|'po'|'group'",
            "",
            f"export const {var} = [",
        ]
        for club, season, result in rows:
            lines.append(f"  {{ club: {js_str(club)}, season: {js_str(season)}, result: {js_str(result)} }},")
        lines += ["];", ""]

        path = ROOT / "src/data" / fname
        path.write_text("\n".join(lines), encoding="utf-8")
        print(f"  → {len(rows):4d} entries  {fname}")


def export_players(con: sqlite3.Connection):
    # All players with at least one squad entry
    player_rows = con.execute(
        "SELECT DISTINCT p.tm_id, p.name, p.birth_date, p.nationality "
        "FROM players p "
        "JOIN squad_entries se ON se.player_id = p.tm_id "
        "ORDER BY p.name"
    ).fetchall()

    lines = [
        "// Auto-generated by scripts/export_european_players_js.py",
        "// ratings are 0 until filled by scrape_fifaindex.py",
        "",
        "export const PLAYERS_EUROPEAN = [",
    ]

    for tm_id, name, birth_date, nationality in player_rows:
        # Positions: primary first, then secondary
        pos_rows = con.execute(
            "SELECT position FROM player_positions WHERE player_id=? ORDER BY is_primary DESC",
            (tm_id,)
        ).fetchall()
        positions = [r[0] for r in pos_rows] or ["CM"]

        birth_date_js = js_str(birth_date) if birth_date else "null"

        # All squad appearances
        season_rows = con.execute(
            "SELECT sc.club_name, s.label "
            "FROM squad_entries se "
            "JOIN season_clubs sc ON sc.season_year=se.season_year AND sc.comp_id=se.comp_id AND sc.club_id=se.club_id "
            "JOIN seasons s ON s.year=se.season_year AND s.comp_id=se.comp_id "
            "WHERE se.player_id=? "
            "ORDER BY s.year",
            (tm_id,)
        ).fetchall()

        seasons_js = "[" + ", ".join(
            f"{{ club: {js_str(club)}, season: {js_str(season)}, rating: 0 }}"
            for club, season in season_rows
        ) + "]"

        pos_js  = "[" + ", ".join(js_str(p) for p in positions) + "]"
        nat_js  = js_str(nationality) if nationality else "null"
        pid_js  = js_str(make_id(name, tm_id))

        lines.append(
            f"  {{ id: {pid_js}, name: {js_str(name)}, "
            f"positions: {pos_js}, birthDate: {birth_date_js}, nationality: {nat_js}, "
            f"seasons: {seasons_js} }},"
        )

    lines += ["];", ""]

    path = ROOT / "src/data/playersEuropean.js"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  → {len(player_rows):5d} players  playersEuropean.js")


if __name__ == "__main__":
    con = sqlite3.connect(DB_PATH)
    print("Exporting participants …")
    export_participants(con)
    print("Exporting players …")
    export_players(con)
    con.close()
    print("Done.")
